### ISSUE TITLE
Access to asset of motions

### ISSUE THREAD

**Issue by leizhu-angus** [openxrlab/xrfeitoria#11]
In your paper SynBody: Synthetic Dataset with Layered Human Models for 3D Human Perception and Modeling, you provide 1,187 motions. How can I access these motions when using xrfeitoria setup_animation functions? Thanks for replying.

**Comment by HaiyiMei** [comment]
Hi @leizhu-angus

- Motions used in Synbody are from [Amass](https://amass.is.tue.mpg.de/index.html). We use `SMPL-X N` that appeared on [download page](https://amass.is.tue.mpg.de/download.php)
- About how to load amass motions, we wrote a new sample code `07_amass.py` in #12
	- It is recommended to run this script in `Blender >= 3.6`
	- These codes are under release, which means you should follow the instructions [here](https://xrfeitoria.readthedocs.io/en/latest/apis/generated/xrfeitoria.factory.init_blender.html#xrfeitoria.factory.init_blender.__init__) with `xf.init_blender(..., replace_plugin=True, dev_plugin=True)`

**Comment by leizhu-angus** [comment]
Hi, thanks for replying. May I also know how you dress these generated smpl-x models as they were naked initially?

**Comment by HaiyiMei** [comment]
> Hi, thanks for replying. May I also know how you dress these generated smpl-x models as they were naked initially?

We built a system to generate garments for SMPL-X models as mentioned in the [paper](https://arxiv.org/pdf/2303.17368.pdf), mainly in Sec 3.1 and Figure 3. You can download our pre-generated SMPL-XL models [here](https://openxlab.org.cn/datasets/OpenXDLab/SynBody/tree/main/Assets).

**Comment by HaiyiMei** [comment]
🥳 We are thrilled to announce the release of 1,000+ new SMPL-XL models! You can download them [here](https://openxlab.org.cn/datasets/OpenXDLab/SynBody/tree/main/Assets).

I'm gonna close this issue. Feel free to reopen it.
