### ISSUE TITLE
SMPL_BODY_BONES

### ISSUE THREAD

**Issue by cjfcsjt** [openxrlab/xrfeitoria#13]
Hi,

I wonder why the joint names in SMPL_BODY_BONES is different from the official SMPL (e.g., the 'left_hand', 'right_hand' is commented) ?

Thanks.

**Comment by Maoxie** [comment]
Hi @cjfcsjt, thank you for your question!

In our pipeline, the 3d human models to be animated are created via the official [SMPL-X Blender Add-on](https://smpl-x.is.tue.mpg.de/download.php). We map the names of SMPL to their counterparts of SMPL-X.

But for bones of `left_hand` and `right_hand` which in SMPL-X have been divided into finger bones such as `left_index1` and `left_thumb1`, their motions couldn't be properly used to drive a SMPL-X model, so they are ignored for simplicity.
