### ISSUE TITLE
MASK and Depth are totally black

### ISSUE THREAD

**Issue by chuanfushen** [openxrlab/xrfeitoria#16]
I run ```python -m samples.blender.05_skeletalmesh_render```
but the generated mask and depth are black.

I have tested the newest code in both macos (blender4.0) and windows(unreal5.1 & blender3.6.5).

**Comment by chuanfushen** [comment]
Your team is awesome! 

 I use your latest update #15, mask and depth can be normally functioned.

**Comment by HaiyiMei** [comment]
😄Thanks for your appreciation. Yes, we fixed the bug in #15, it will be merged with a new feature. Feel free to reopen this issue if you need to.
