### ISSUE TITLE
How to generate SMPL-XL?

### ISSUE THREAD

**Issue by chuanfushen** [openxrlab/xrfeitoria#17]
Thanks for your great work!

As you mentioned in https://github.com/openxrlab/xrfeitoria/issues/11#issuecomment-1801441338, I would like to know if the automated script generated to add the garment to SMPL-X will be released.

**Comment by chuanfushen** [comment]
To be more specifically, I would like to know any plan to release code related to human model creation to generate layered
human models.

**Comment by HaiyiMei** [comment]
Appreciate your interest in generating SMPL-XL (layered human model). This section significantly relies on the license of digital assets for secondary publishing, which in turn influences the design of our proprietary code that is not intended for open-source distribution. 

Nevertheless, we are diligently preparing to pick some more 1,000 SMPL-XL models to release soon.

**Comment by HaiyiMei** [comment]
🥳 We are thrilled to announce the release of 1,000+ new SMPL-XL models! You can download them [here](https://openxlab.org.cn/datasets/OpenXDLab/SynBody/tree/main/Assets).

I'm gonna close this issue. Feel free to reopen it.

**Comment by chuanfushen** [comment]
That is awesome!
