### ISSUE TITLE
some bugs when I run 'xf-render bunny.obj'

### ISSUE THREAD

**Issue by Andyen512** [openxrlab/xrfeitoria#18]
in __init__                                                                                      │
│                                                                                                  │
│   200 │   │   )                                                                                  │
│   201 │   │   self._rpc_runner.start()                                                           │
│   202 │   │   self.utils.init_scene_and_collection(default_level_blender, self._cleanup)         │
│ ❱ 203 │   │   self.utils.set_env_color(color=(1.0, 1.0, 1.0, 1.0))                               │
│   204 │                                                                                          │
│   205 │   def __enter__(self) -> 'init_blender':                                                 │
│   206 │   │   return self                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: '\'\\\'bpy_prop_collection[key]: key "Background" not found\\\'\'  File "/Users/xxx/anaconda3/envs/synbody/lib/python3.9/site-packages/xrfeitoria/utils/functions/blender_functions.py", line 119'

**Comment by HaiyiMei** [comment]
Could you share the version of Blender you are currently using?

**Comment by Andyen512** [comment]
3.1.2 in MaCOS

**Comment by Andyen512** [comment]
Maybe not the version issue? I encounter the same problem when I switch Blender to both version 3.2 and 3.5.

**Comment by HaiyiMei** [comment]
Thanks for the report. I'm currently unable to reproduce this bug. Can you try this in your bash or directly in blender's python-console:
```bash
/path/to/blender -b --python-console  # open blender as python-console

# input these lines
>>> import bpy
>>> print(bpy.context.scene.world.node_tree.nodes.keys())
```
Ideally, you would get this: `['World Output', 'Background']`

By default, when you open a new project in blender, the nodes of the world should contain `['World Output', 'Background']`, like:
![image](https://github.com/openxrlab/xrfeitoria/assets/35397764/7639a183-3946-48d3-9a3a-2957d59d712d)

**Comment by Andyen512** [comment]
<img width="2123" alt="image" src="https://github.com/openxrlab/xrfeitoria/assets/74585868/de84be71-5064-4504-b741-ccacab8cd872">
I get the output of: ['World Output', 'Background'], and the nodes of the world in blender is also correct, so I'm confused.

**Comment by Andyen512** [comment]
bug solved. Due to setting Blender's language to Chinese, the output result is ['世界输出'，‘背景’].

**Comment by HaiyiMei** [comment]
Noticed. In the future version of XRFeitoria will add a warning if the setting of blender is not in default.
Thanks for your report.
