### ISSUE TITLE
May I ask a question about SynBody motion data

### ISSUE THREAD

**Issue by Time-Lord12th** [openxrlab/xrfeitoria#20]
Thanks for your work. I'm trying to render some synbody models in my camera setting, rendering T-pose is easy. But I only find 3 motion models in .fbx format(e.g. `actor.setup_animation(animation_path=https://openxrlab-share.oss-cn-hongkong.aliyuncs.com/xrfeitoria/tutorials/assets/SMPL-XL/walking__15_01.fbx)`), could you please tell me how to create more motion models, maybe from some smpl-x.npy?

**Comment by HaiyiMei** [comment]
Yes, you can use npy file. Please refer to https://github.com/openxrlab/xrfeitoria/blob/main/samples/blender/07_amass.py.

In this sample, we use `.npz` file download from AMASS dataset as motion. To be noticed, in #15 we gonna bring this feature to UE. This will be merged soon, and a new version of XRFeitoria will be released.

**Comment by Time-Lord12th** [comment]
> Yes, you can use npy file. Please refer to https://github.com/openxrlab/xrfeitoria/blob/main/samples/blender/07_amass.py.
> 
> In this sample, we use `.npz` file download from AMASS dataset as motion. To be noticed, in #15 we gonna bring this feature to UE. This will be merged soon, and a new version of XRFeitoria will be released.

Thank you for your answer. It helps me a lot.
