### ISSUE TITLE
How to render with depth and normal as well as meshes with texture?

### ISSUE THREAD

**Issue by jinnan-chen** [openxrlab/xrfeitoria#31]
Also, where to set camera extrinsics and intrinsics?

**Comment by HaiyiMei** [comment]
Sorry for the late reply. 
You can refer to our [tutorial](https://xrfeitoria.readthedocs.io/en/latest/src/tutorials/01_get_started.html) which contains a full pipeline of importing meshes with textures, and render it with different [render passes](https://xrfeitoria.readthedocs.io/en/latest/apis/generated/xrfeitoria.data_structure.models.RenderPass.html).

**Comment by HaiyiMei** [comment]
As for camera parameters, we don't support using intrinsic and extrinsic matrices directly yet. But you can set the camera's location, rotation, and fov. You can follow the doc [here](https://xrfeitoria.readthedocs.io/en/latest/apis/generated/xrfeitoria.camera.camera_blender.CameraBlender.html#xrfeitoria.camera.camera_blender.CameraBlender.spawn) and also from the tutorials.
Plus, we have tools of converting [blender](https://github.com/openxrlab/xrfeitoria/blob/main/xrfeitoria/utils/converter.py#L300)/[unreal](https://github.com/openxrlab/xrfeitoria/blob/main/xrfeitoria/camera/camera_parameter.py#L180) convention to opencv convention. So maybe you can reverse it, and use your camera parameters.
